name: '自身のMavenリポジトリにPush'

on: [push]
#  push:
#    branches:
#      - master

jobs:
  Reflect-To-My-Maven:
    runs-on: ubuntu-latest
    steps:
      - name: 現ブランチからチェックアウト
        uses: actions/checkout@v2

      - name: 実行許可を付与
        run: cd ${{ github.workspace }} && chmod 777 ${{ github.workspace }}/gradlew

      - name: Publish用にビルド
        run: cd ${{ github.workspace }} && ./gradlew publish

      - name: Mavenリポジトリを取得
        run: git clone https://github.com/Wansuko-cmd/maven.git

      - name: git configを設定
        run: git config --global user.email "action@github.com" && git config --global user.name "Wansuko-cmd"

      - name: ビルドしたものをローカルのMavenリポジトリに反映
        run: cd ${{ github.workspace }} && cp -v -r ./lib/build/publish/com ./maven

      - name: ローカルのMavenリポジトリの変更を追加
        run: cd ${{ github.workspace }}/maven && git add *

      - name: ローカルのMavenリポジトリの変更をコミット
        run: cd ${{ github.workspace }}/maven && git commit -m "[update] Content-Type-Checkerのアップデート"

      - name: Mavenリポジトリをチェックアウト
        run: cd ${{ github.workspace }}/maven && git checkout -b "update/content-type-checker"

      - name: ローカルのMavenの変更内容をプッシュ
        run: cd ${{ github.workspace }}/maven && git push origin update/content-type-checker
